#pragma once

#include <QWidget>

/*!
* Endpoint for all messages generated by the various software components.
* Displays all messages using a \class QTextEdit component.
*/
class Logger : public QWidget
{
	Q_OBJECT
		
public:
	/*!
	* Class constructor.
	* @param [in] parent Parent widget
	*/
	Logger(QWidget* parent = Q_NULLPTR);

signals:
	/*!
	* Signal generated when the logger's hide button is clicked
	*/
	void hideClicked(bool visible);

private:
	
};

